# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b0a911e5022e27c52059b9695259b2121b0c231017ab913dc733884805f662bfe79a035e6e2b149872b78dd1620d29f07846a5df2bd02f446728751c101274b7

test:
  secret_key_base: 5d3c4ba4517f1b2410acb03eaf26c4a3c4a512e8a67074c16bd4128e6d6f49611daae9c8b69d2184fa77667454c3f90478649aa2d8ba54d061152aed76732d44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
